"""Initial migration with photo fields for auctions

Revision ID: 2fdb34bb6864
Revises: 
Create Date: 2025-12-25 03:24:55.097099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdb34bb6864'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyers_email'), ['email'], unique=True)

    op.create_table('farmers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('caste_category', sa.String(length=50), nullable=True),
    sa.Column('is_physically_handicapped', sa.Boolean(), nullable=True),
    sa.Column('permanent_address', sa.String(length=500), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('taluka', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('total_land_area_hectares', sa.Float(), nullable=False),
    sa.Column('land_area_gunthas', sa.Float(), nullable=True),
    sa.Column('land_holder_type', sa.String(length=50), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('current_crops', sa.String(length=500), nullable=True),
    sa.Column('is_oilseed_farmer', sa.Boolean(), nullable=True),
    sa.Column('oilseed_enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('is_pm_kisan_beneficiary', sa.Boolean(), nullable=True),
    sa.Column('pm_kisan_reference_id', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('water_type', sa.String(length=50), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('land_unit', sa.String(length=20), nullable=True),
    sa.Column('coins_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmers_farmer_id'), ['farmer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_farmers_phone_number'), ['phone_number'], unique=True)

    op.create_table('market_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('commodity_name', sa.String(length=100), nullable=False),
    sa.Column('market_name', sa.String(length=100), nullable=False),
    sa.Column('market_state', sa.String(length=50), nullable=True),
    sa.Column('market_district', sa.String(length=100), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('trading_volume', sa.Float(), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redemption_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('coin_cost', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('offer_type', sa.String(length=50), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('stock_limit', sa.Integer(), nullable=True),
    sa.Column('stock_redeemed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scheme_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scheme_type', sa.String(length=50), nullable=False),
    sa.Column('focus_area', sa.String(length=100), nullable=False),
    sa.Column('focus_color', sa.String(length=20), nullable=True),
    sa.Column('benefit_amount', sa.String(length=255), nullable=False),
    sa.Column('eligibility_criteria', sa.Text(), nullable=False),
    sa.Column('apply_steps', sa.Text(), nullable=True),
    sa.Column('external_link', sa.String(length=255), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('required_documents', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schemes_scheme_code'), ['scheme_code'], unique=True)

    op.create_table('auctions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_quintals', sa.Float(), nullable=False),
    sa.Column('quality_grade', sa.String(length=50), nullable=True),
    sa.Column('base_price_per_quintal', sa.Float(), nullable=False),
    sa.Column('minimum_bid_increment', sa.Float(), nullable=True),
    sa.Column('current_highest_bid', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('storage_location', sa.String(length=255), nullable=True),
    sa.Column('photo1_path', sa.String(length=255), nullable=True),
    sa.Column('photo2_path', sa.String(length=255), nullable=True),
    sa.Column('photo3_path', sa.String(length=255), nullable=True),
    sa.Column('photo4_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auctions_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('coin_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('total_coins', sa.Integer(), nullable=True),
    sa.Column('available_coins', sa.Integer(), nullable=True),
    sa.Column('redeemed_coins', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id')
    )
    op.create_table('crop_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_quintal', sa.Float(), nullable=False),
    sa.Column('expected_price', sa.Float(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('photo1_path', sa.String(length=255), nullable=True),
    sa.Column('photo2_path', sa.String(length=255), nullable=True),
    sa.Column('photo3_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmer_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('match_percentage', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ai_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_recommendations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_recommendations_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('farmer_redemptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('coins_spent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('redemption_code', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['redemption_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('redemption_code')
    )
    op.create_table('farmer_rewards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('points_from_switching', sa.Float(), nullable=True),
    sa.Column('points_from_soil_test', sa.Float(), nullable=True),
    sa.Column('points_from_sales', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iot_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('device_serial', sa.String(length=100), nullable=True),
    sa.Column('device_mac', sa.String(length=20), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('installed', sa.Boolean(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('wifi_ssid', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('soil_dry_value', sa.Integer(), nullable=True),
    sa.Column('soil_wet_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_mac')
    )
    with op.batch_alter_table('iot_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iot_devices_device_serial'), ['device_serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_iot_devices_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('action_link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('mandi_name', sa.String(length=100), nullable=True),
    sa.Column('alert_price', sa.Float(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_quintal', sa.Float(), nullable=False),
    sa.Column('expected_price', sa.Float(), nullable=False),
    sa.Column('harvest_date', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('farmer_name', sa.String(length=200), nullable=True),
    sa.Column('farmer_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('buyer_price', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subsidy_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('application_data', sa.Text(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('application_pdf_path', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('auction_id', sa.String(length=36), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auction_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auction_notifications_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auction_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('bids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('auction_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('bid_price_per_quintal', sa.Float(), nullable=False),
    sa.Column('bid_total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_buyer_id'), ['buyer_id'], unique=False)

    op.create_table('buyer_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_mobile', sa.String(length=20), nullable=True),
    sa.Column('buyer_location', sa.String(length=255), nullable=True),
    sa.Column('buyer_company', sa.String(length=255), nullable=True),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_quintal', sa.Float(), nullable=False),
    sa.Column('location_wanted', sa.String(length=255), nullable=True),
    sa.Column('district_wanted', sa.String(length=100), nullable=True),
    sa.Column('initial_price', sa.Float(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('sell_request_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['sell_request_id'], ['sell_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coin_balance_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coin_balance_id'], ['coin_balances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('land_area_hectares', sa.Float(), nullable=True),
    sa.Column('field_location', sa.String(length=255), nullable=True),
    sa.Column('preferred_installation_date', sa.Date(), nullable=True),
    sa.Column('farmer_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_device_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assigned_device_id'], ['iot_devices.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_requests_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('sell_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['sell_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('heat_index', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('soil_raw', sa.Integer(), nullable=True),
    sa.Column('soil_temp', sa.Float(), nullable=True),
    sa.Column('light', sa.Float(), nullable=True),
    sa.Column('light_raw', sa.Integer(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['iot_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_readings_received_at'), ['received_at'], unique=False)

    op.create_table('chats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('sell_request_id', sa.String(length=36), nullable=True),
    sa.Column('buyer_offer_id', sa.String(length=36), nullable=True),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['buyer_offer_id'], ['buyer_offers.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['sell_request_id'], ['sell_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counter_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('auction_id', sa.String(length=36), nullable=False),
    sa.Column('bid_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('counter_price_per_quintal', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counter_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counter_offers_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counter_offers_bid_id'), ['bid_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counter_offers_buyer_id'), ['buyer_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    with op.batch_alter_table('counter_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counter_offers_buyer_id'))
        batch_op.drop_index(batch_op.f('ix_counter_offers_bid_id'))
        batch_op.drop_index(batch_op.f('ix_counter_offers_auction_id'))

    op.drop_table('counter_offers')
    op.drop_table('chats')
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_readings_received_at'))

    op.drop_table('sensor_readings')
    op.drop_table('sell_photos')
    with op.batch_alter_table('device_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_requests_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_device_requests_created_at'))

    op.drop_table('device_requests')
    op.drop_table('coin_transactions')
    op.drop_table('buyer_offers')
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_buyer_id'))
        batch_op.drop_index(batch_op.f('ix_bids_auction_id'))

    op.drop_table('bids')
    with op.batch_alter_table('auction_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auction_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_auction_notifications_auction_id'))

    op.drop_table('auction_notifications')
    op.drop_table('subsidy_applications')
    op.drop_table('sell_requests')
    op.drop_table('price_alerts')
    op.drop_table('otp_records')
    op.drop_table('notifications')
    with op.batch_alter_table('iot_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iot_devices_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_iot_devices_device_serial'))

    op.drop_table('iot_devices')
    op.drop_table('farmer_rewards')
    op.drop_table('farmer_redemptions')
    with op.batch_alter_table('farmer_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_recommendations_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_farmer_recommendations_created_at'))

    op.drop_table('farmer_recommendations')
    op.drop_table('crop_listings')
    op.drop_table('coin_balances')
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auctions_farmer_id'))

    op.drop_table('auctions')
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schemes_scheme_code'))

    op.drop_table('schemes')
    op.drop_table('redemption_offers')
    op.drop_table('market_prices')
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmers_phone_number'))
        batch_op.drop_index(batch_op.f('ix_farmers_farmer_id'))

    op.drop_table('farmers')
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyers_email'))

    op.drop_table('buyers')
    # ### end Alembic commands ###
