"""sell request tables

Revision ID: 350376b0df5c
Revises: ad83b660a681
Create Date: 2025-12-03 02:19:55.698982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350376b0df5c'
down_revision = 'ad83b660a681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_quintal', sa.Float(), nullable=False),
    sa.Column('expected_price', sa.Float(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('photo1_path', sa.String(length=255), nullable=True),
    sa.Column('photo2_path', sa.String(length=255), nullable=True),
    sa.Column('photo3_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_quintal', sa.Float(), nullable=False),
    sa.Column('expected_price', sa.Float(), nullable=False),
    sa.Column('harvest_date', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('farmer_name', sa.String(length=200), nullable=True),
    sa.Column('farmer_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('buyer_price', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_mobile', sa.String(length=20), nullable=True),
    sa.Column('buyer_location', sa.String(length=255), nullable=True),
    sa.Column('initial_price', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['crop_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['sell_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sell_photos')
    op.drop_table('buyer_offers')
    op.drop_table('sell_requests')
    op.drop_table('crop_listings')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
