"""added onboarding fields

Revision ID: ad83b660a681
Revises: 
Create Date: 2025-12-03 00:16:03.545728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad83b660a681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('irrigation_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('harvest_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('land_unit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_column('land_unit')
        batch_op.drop_column('harvest_date')
        batch_op.drop_column('irrigation_type')

    # ### end Alembic commands ###
